<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-VMNQCVL" ignored="0" name="Parallel Tests" tests="9" failures="4" timestamp="2022-06-03T20:32:10 EET" time="50.98" errors="0">
  <testcase name="Register" time="1.63" classname="tests.TestRegistrationCSV">
    <failure type="java.lang.AssertionError" message="expected [] but found [Your registration completed]">
      <![CDATA[java.lang.AssertionError: expected [] but found [Your registration completed]
at tests.TestRegistrationCSV.Register(TestRegistrationCSV.java:40)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- Register -->
  <testcase name="Register" time="1.738" classname="tests.TestRegistrationJSON">
    <failure type="java.lang.AssertionError" message="expected [] but found [Your registration completed]">
      <![CDATA[java.lang.AssertionError: expected [] but found [Your registration completed]
at tests.TestRegistrationJSON.Register(TestRegistrationJSON.java:31)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- Register -->
  <testcase name="Register" time="1.489" classname="tests.TestRegistration">
    <failure type="java.lang.AssertionError" message="expected [] but found [Your registration completed]">
      <![CDATA[java.lang.AssertionError: expected [] but found [Your registration completed]
at tests.TestRegistration.Register(TestRegistration.java:31)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- Register -->
  <testcase name="Register" time="6.236" classname="tests.TestRegistrationExcel"/>
  <testcase name="Register" time="8.384" classname="tests.TestRegistrationExcel"/>
  <testcase name="Register" time="5.034" classname="tests.TestRegistrationExcel"/>
  <testcase name="login" time="4.601" classname="tests.TestLoginPage"/>
  <testcase name="login" time="3.324" classname="tests.TestLoginPage">
    <failure type="java.lang.AssertionError" message="expected [Your username is invalid!
ﾃ余 but found [You logged into a secure area!
ﾃ余">
      <![CDATA[java.lang.AssertionError: expected [Your username is invalid!
ﾃ余 but found [You logged into a secure area!
ﾃ余
at tests.TestLoginPage.login(TestLoginPage.java:33)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="testNumberOfLinks" time="0.078" classname="tests.TestHomePage"/>
</testsuite> <!-- Parallel Tests -->
